# Exported from Render on 2024-09-29T07:29:24Z
services:
- type: web
  name: OCR
  runtime: python
  repo: https://github.com/Ankhilam531/OCR
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
version: "1"
